version: '3.8'

services:
  postgres:
    image: stock-manager-database
    container_name: stock-manager-application-database
    environment:
      POSTGRES_DB: DALYDA
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailHog:
    image: mailhog/mailhog:latest
    container_name: DALYDA-mailHog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI

  app:
    image: stock-manager-app
    container_name: stock-manager-application
    depends_on:
      - postgres
      - mailHog
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/DALYDA
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"

      SPRING_MAIL_HOST: mailHog
      SPRING_MAIL_PORT: 1025
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "false"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "false"
      SPRING_MAIL_FROM: no-reply@stockmanager.com

      SERVER_PORT: 8080
      APP_ENVIRONMENT: development
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: 86400000

    ports:
      - "8080:8080"
    volumes:
      - ./target/*.jar:/app.jar
      - ./logs:/logs
    command: java -jar /app.jar

volumes:
  postgres_data:
